### ISSUE TITLE
Network policy update required

### ISSUE THREAD

**Issue by mnadeem** [jharting/openshift-rabbitmq-cluster#19]
```
2022-02-24 19:27:55.565 [warning] <0.274.0> Could not auto-cluster with node rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local: {badrpc,nodedown}
2022-02-24 19:27:55.565 [info] <0.274.0> Trying to join discovered peers failed. Will retry after a delay of 500 ms, 6 retries left...
```
Following fixes the above issue, in effect need to add both ingress and egreee

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-internal-access
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: rabbitmq
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: rabbitmq
```
